import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header"

const font = IBM_Plex_Sans({
  weight: ["400", "600"],
  subsets: ["latin", "cyrillic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
